tap "mongodb/brew"
tap "nikitabobko/tap"
tap "omnisharp/omnisharp-roslyn"
tap "oven-sh/bun"

brew "git"
brew "bash"
brew "bash-completion@2"
brew "buf"
brew "carapace"
brew "chafa"
brew "coreutils"
brew "curl"
brew "delve"
brew "fd"
brew "findutils"
brew "fzf"
brew "gawk"
brew "gh"
brew "glow"
brew "gnupg"
brew "go"
brew "goimports"
brew "golang-migrate"
brew "grep"
brew "helix"
brew "htop"
brew "jq"
brew "lazygit"
brew "moreutils"
brew "nx"
brew "pandoc"
brew "protoc-gen-go"
brew "protoc-gen-go-grpc"
brew "protoc-gen-js"
brew "pygments"
brew "ripgrep"
brew "sc-im"
brew "shellcheck"
brew "starship"
brew "stern"
brew "tmux"
brew "tree"
brew "wget"
brew "yq"
brew "oven-sh/bun/bun"

# language servers
brew "gopls"
brew "marksman"
brew "tailwindcss-language-server"
brew "taplo"
brew "typescript-language-server"
brew "vscode-langservers-extracted"
brew "yaml-language-server"
brew "omnisharp/omnisharp-roslyn/omnisharp"

# formatters
brew "prettier"

# work
brew "asdf"
brew "tailscale"

# casks
cask "1password"
cask "1password-cli"
cask "aerospace"
# cask "alacritty"
cask "dbeaver-community"
cask "dotnet-sdk"
cask "gimp"
cask "github"
cask "ghostty"
cask "postman"
cask "temurin"
